[package]
name = "maastossa"
version = "0.1.0"
authors = ["Stefan Röhrbein <gitzozgame@googlemail.com>"]
edition = "2018"

[dependencies]
noise = "0.5.1"
rand = "0.3"
piston = "0.42.0"
piston2d-graphics = "0.30.0"
pistoncore-glutin_window = "0.54.0"
piston2d-opengl_graphics = "0.59.0"